fragment bucket on GrantBucket {
    bucketGroup {
      id
      name
    }
    grants
    recipients
    funders
    currencies {
        currency
        total
        mean
    }
}

query fetchGrants(
    $dataset: String!, 
    $funders: [String],
    $funderTypes: [String],
    $grantProgrammes: [String], 
    $area: [String], 
    $orgtype: [String],
    $awardDates: MaxMin
){
    grants(
        dataset: $dataset,
        funders: $funders,
        funderTypes: $funderTypes,
        grantProgrammes: $grantProgrammes,
        area: $area,
        orgtype: $orgtype,
        awardDates: $awardDates
    ) {
        summary {
            grants
            recipients
            funders
            maxDate
            minDate
            currencies {
                currency
                total
                mean
                grants
            }
        }
        byFunder {
            ...bucket
        }
        byFunderType {
            ...bucket
        }
        byGrantProgramme {
            ...bucket
        }
        byAmountAwarded {
            ...bucket
        }
        byAwardYear {
            ...bucket
        }
        byAwardDate {
            bucketGroup {
                id
            }
            grants
        }
        byOrgType {
            ...bucket
        }
        byOrgAge {
            ...bucket
        }
        byOrgSize {
            ...bucket
        }
        byCountryRegion {
            ...bucket
        }
    }
}