// 'use strict';

// const e = React.createElement;

// class ResultsPage extends React.Component {
//     constructor(props) {
//         super(props);
//         this.state = { liked: false };
//     }

//     render() {
//         if (this.state.liked) {
//             return 'You liked this.';
//         }

//         return e(
//             'button',
//             { onClick: () => this.setState({ liked: true }) },
//             'Like'
//         );
//     }
// }

// const domContainer = document.querySelector('#dashboard-container');
// ReactDOM.render(e(ResultsPage), domContainer);

function PageHeader(props){
    return <div className="results-page__header">
        <div className="wrapper">
            <a href="/">360<span style={{ color: 'rgb(156, 31, 97)' }}>Insights</span></a>
        </div>
    </div>
}

function FilterForm(props){
    return <form id="filters-form">
        <div className="cf">
            <div id="dashboard-filter-items"></div>
        </div>
    </form>
}

function Sidebar(props){
    return <aside className="results-page__menu">
        <a href="/?file-selection-modal" className="results-page__menu__back"><i className="material-icons">arrow_back</i>
            Select another dataset</a>
        <h3 className="results-page__menu__section-title">Filters</h3>
        <FilterForm />
    </aside>    
}

function DashboardHeader(props){
    return <section id="dashboard-header" className="results-page__body__content">
        <h5 className="results-page__body__content__grants-made-by">Grants made by </h5>
        <h1 className="results-page__body__content__header">
            <span className="results-page__body__content__title funder-title"
                style={{ opacity: 1 }}></span>
            <span className="date-prefix"> between </span>
            <span className="results-page__body__content__date date-range"></span>
        </h1>
        <div className="results-page__body__content__spheres">
            <div className="results-page__body__content__sphere" style={{ backgroundColor: 'rgb(156, 32, 97)' }}>
                <p className="total-grants"></p>
                <h4 className="">grants</h4>
            </div>
            <div className="results-page__body__content__sphere" style={{ backgroundColor: 'rgb(244, 131, 32)' }}>
                <p className="total-recipients"></p>
                <h4 className="">recipients</h4>
            </div>
            <div className="results-page__body__content__sphere" style={{ backgroundColor: 'rgb(83, 170, 221)' }}>
                <p className="total-amount"></p>
                <h4 className="total-amount-suffix"></h4>
                <h4 className="">Total</h4>
            </div>
            <div className="results-page__body__content__sphere"
                style={{ backgroundColor: 'rgb(205, 220, 43)', color: 'rgb(11, 40, 51)' }}>
                <p className="mean-amount"></p>
                <h4 className="mean-amount-suffix"></h4>
                <h4 className="">(Average grant)</h4>
            </div>
        </div>
        <div className="results-page__body__section-attribution">
            <p><strong>From the 360Giving data registry</strong></p>
            <p>
                Published by
                            <a href="http://www.essexcommunityfoundation.org.uk/index.php"
                    target="_blank">Essex Community Foundation</a>
                with a
                            <a href="https://creativecommons.org/licenses/by/4.0/"
                    target="_blank">Creative Commons Attribution 4.0 International (CC BY 4.0)</a>
                licence.
                        </p>
            <p><a href="http://www.essexcommunityfoundation.org.uk/images/uploads/ECF_Grants_Awarded.xlsx"
                target="_blank">Download original file</a>(xlsx)
                        </p>
        </div>
    </section>
}

function DashboardOutput(props){
    return <section id="dashboard-output" className="results-page__body__content"></section>
}

function WhatsNext(props){
    return <section id="whats-next" className="results-page__body__whats-next">
        <h3 className="results-page__body__whats-next__title">What next?</h3>
        <div>
            <p><strong>1. Do your own analysis</strong><br />You can download the data
                generated by 360Insights to analyse yourself in Excel
                or using CSV with other software. The download includes all the additional information we've
                added to the data,
                like charity data or geo data from the postcodes.
                        </p>
            <ul>
                <li><a id="file-download-csv" href="/data/download/a002400000p0ykGAAQ.csv" target="_blank">CSV
                                    Download</a></li>
                <li><a id="file-download-excel" href="/data/download/a002400000p0ykGAAQ.xlsx"
                    target="_blank">Excel Download</a></li>
            </ul>
        </div>
        <div>
            <p><strong>2. Try other tools and get inspired</strong><br />There are lots
                of other services you can use to explore and visualise this kind of data. Here are some of our
                favourites:
                        </p>
            <ul>
                <li><a href="https://flourish.studio/">Flourish</a></li>
                <li><a href="https://databasic.io/">Databasic</a></li>
                <li><a href="https://carto.com/">Carto</a></li>
                <li><a href="https://challenge.threesixtygiving.org/">360Giving's visualisation challenge</a>
                </li>
            </ul>
        </div>
        <div>
            <p><strong>3. Make the most of your data</strong><br />Grants data is at its
                most powerful when it is linked to other datasets.
                As the data in this case included postcodes and organisation identifiers
                we've been able to map and link it to other datasets. If you’d like one-to-one
                guidance on how to use data to support your grantmaking, book an
                            <a href="https://www.threesixtygiving.org/support/officehours/">Office Hour</a>
            </p>
        </div>
        <div>
            <p><strong>4. Give us feedback!</strong><br />If you like 360Insights, found
                a bug or want to request features, email
                            <a href="mailto:labs@threesixtygiving.org">labs@threesixtygiving.org</a>.
                            <br />You could share what you’ve learned with your
                communities (perhaps including
                screenshots or the URL) using the hashtag
                            <a
                    href="https://twitter.com/search?f=tweets&amp;vertical=default&amp;q=%23360Insights&amp;src=typd">#360Insights</a>
                on Twitter.
                        </p>
        </div>
    </section>
}

function DashboardFooter(props){
    return <div>
        <footer className="light">
            <ul className="footer__social">
                <li><a href="https://github.com/ThreeSixtyGiving/"><img src="/images/icon-github.png"
                    title="Github" /></a></li>
                <li><a href="https://twitter.com/360giving"><img src="/images/icon-twitter.png"
                    title="Twitter" /></a></li>
            </ul>
            <div className="flex-wrapper">
                <section>
                    <div className="footer__navigation--title">
                        &nbsp;
                                    <ul className="footer__navigation">
                            <li><a href="https://www.threesixtygiving.org/contact/">Contact</a></li>
                        </ul>
                    </div>
                </section>
                <section>
                    <ul className="footer__navigation footer__navigation--headless">
                        <li><a href="/about">About</a></li>
                    </ul>
                </section>
                <section>
                    <p style={{ fontWeight: 300 }}>
                        <a href="https://www.threesixtygiving.org/">
                            <img src="/images/360giving-white@4x.png" style={{ opacity: 0.5 }} width="192" /><br />
                        </a>
                        Open data for more effective grantmaking
                                </p>
                </section>
            </div>
            <div className="footer__divider">
                <hr />
                <div className="footer__divider__columns">
                    <p>
                        <a href="/about#privacy">Privacy Notice</a> |
                                    <a href="/about#terms">Terms &amp; Conditions</a> |
                                    <a href="/about#cookies">Cookie Policy</a><br />
                        <a href="http://www.threesixtygiving.org/take-down-policy/">Take Down Policy</a> |
                                    <a href="https://creativecommons.org/licenses/by/4.0/">License</a>
                    </p>
                    <p className="footer__credits">
                        Created by <a href="https://dkane.net" rel="noopener" target="_blank">David Kane</a>.
                                    Design by <a href="https://www.ccmdesign.ca/" rel="noopener"
                            target="_blank">ccm.design</a><br />
                        360Giving: Company <a href="https://beta.companieshouse.gov.uk/company/09668396"
                            rel="noopener" target="_blank">09668396</a>
                        Charity <a
                            href="http://beta.charitycommission.gov.uk/charity-details/?regid=1164883&amp;subid=0"
                            rel="noopener" target="_blank">1164883</a>
                    </p>
                </div>
            </div>
        </footer>
    </div>
}

function Dashboard(props){
    return <React.Fragment>
        <PageHeader />
        <div className="results-page__app">
            <Sidebar />        
            <div className="results-page__body">
                <DashboardHeader />
                <DashboardOutput />
                <WhatsNext />
                <DashboardFooter />
            </div>
        </div>
    </React.Fragment>
}

ReactDOM.render(
    <Dashboard />,
    document.getElementById('dashboard-container')
);