import React from 'react';

export const WhatsNext = function(props) {
    return <section id="whats-next" className="results-page__body__whats-next">
        <h3 className="results-page__body__whats-next__title">What next?</h3>
        <div>
            <p><strong>1. Do your own analysis</strong><br />You can download the data
                generated by 360Insights to analyse yourself in Excel
                or using CSV with other software. The download includes all the additional information we've
                added to the data,
                like charity data or geo data from the postcodes.
                        </p>
            <ul>
                <li><a id="file-download-csv" href="/data/download/a002400000p0ykGAAQ.csv" target="_blank">CSV
                                    Download</a></li>
                <li><a id="file-download-excel" href="/data/download/a002400000p0ykGAAQ.xlsx"
                    target="_blank">Excel Download</a></li>
            </ul>
        </div>
        <div>
            <p><strong>2. Try other tools and get inspired</strong><br />There are lots
                of other services you can use to explore and visualise this kind of data. Here are some of our
                favourites:
                        </p>
            <ul>
                <li><a href="https://flourish.studio/">Flourish</a></li>
                <li><a href="https://databasic.io/">Databasic</a></li>
                <li><a href="https://carto.com/">Carto</a></li>
                <li><a href="https://challenge.threesixtygiving.org/">360Giving's visualisation challenge</a>
                </li>
            </ul>
        </div>
        <div>
            <p><strong>3. Make the most of your data</strong><br />Grants data is at its
                most powerful when it is linked to other datasets.
                As the data in this case included postcodes and organisation identifiers
                we've been able to map and link it to other datasets. If you’d like one-to-one
                guidance on how to use data to support your grantmaking, book an
                            <a href="https://www.threesixtygiving.org/support/officehours/">Office Hour</a>
            </p>
        </div>
        <div>
            <p><strong>4. Give us feedback!</strong><br />If you like 360Insights, found
                a bug or want to request features, email
                            <a href="mailto:labs@threesixtygiving.org">labs@threesixtygiving.org</a>.
                            <br />You could share what you’ve learned with your
communities (perhaps including
screenshots or the URL) using the hashtag
                            <a
                    href="https://twitter.com/search?f=tweets&amp;vertical=default&amp;q=%23360Insights&amp;src=typd">#360Insights</a>
                on Twitter.
                        </p>
        </div>
    </section>
}
