"""org table

Revision ID: 0f2e975ac1a6
Revises: 
Create Date: 2019-03-01 09:44:40.910107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2e975ac1a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('orgid', sa.Integer(), nullable=False),
    sa.Column('charity_number', sa.String(), nullable=True),
    sa.Column('company_number', sa.String(), nullable=True),
    sa.Column('date_registered', sa.Date(), nullable=True),
    sa.Column('date_removed', sa.Date(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('latest_income', sa.BigInteger(), nullable=True),
    sa.Column('latest_income_date', sa.Date(), nullable=True),
    sa.Column('org_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('orgid')
    )
    op.create_index(op.f('ix_organisation_charity_number'), 'organisation', ['charity_number'], unique=False)
    op.create_index(op.f('ix_organisation_company_number'), 'organisation', ['company_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisation_company_number'), table_name='organisation')
    op.drop_index(op.f('ix_organisation_charity_number'), table_name='organisation')
    op.drop_table('organisation')
    # ### end Alembic commands ###
