"""empty message

Revision ID: 1a46d2911914
Revises: e152bfbce39c
Create Date: 2019-09-04 22:43:00.431752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a46d2911914'
down_revision = 'e152bfbce39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant', sa.Column('amountAwardedBand', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoCtry', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoCty', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoImd', sa.Integer(), nullable=True))
    op.add_column('grant', sa.Column('geoImdBand', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoLat', sa.Float(), nullable=True))
    op.add_column('grant', sa.Column('geoLaua', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoLong', sa.Float(), nullable=True))
    op.add_column('grant', sa.Column('geoOac11', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoPcon', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoRgn', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoRu11ind', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('plannedDates_durationBand', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_ageAtGrant', sa.Integer(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_ageAtGrantBands', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_idCanonical', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_latestIncome', sa.BigInteger(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_latestIncomeBand', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_latestIncomeDate', sa.Date(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_registrationDate', sa.Date(), nullable=True))
    op.create_index(op.f('ix_grant_amountAwarded'), 'grant', ['amountAwarded'], unique=False)
    op.create_index(op.f('ix_grant_amountAwardedBand'), 'grant', ['amountAwardedBand'], unique=False)
    op.create_index(op.f('ix_grant_awardDate'), 'grant', ['awardDate'], unique=False)
    op.create_index(op.f('ix_grant_awardDateYear'), 'grant', ['awardDateYear'], unique=False)
    op.create_index(op.f('ix_grant_geoCtry'), 'grant', ['geoCtry'], unique=False)
    op.create_index(op.f('ix_grant_geoCty'), 'grant', ['geoCty'], unique=False)
    op.create_index(op.f('ix_grant_geoImdBand'), 'grant', ['geoImdBand'], unique=False)
    op.create_index(op.f('ix_grant_plannedDates_durationBand'), 'grant', ['plannedDates_durationBand'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_ageAtGrantBands'), 'grant', ['recipientOrganization_ageAtGrantBands'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_idCanonical'), 'grant', ['recipientOrganization_idCanonical'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_latestIncomeBand'), 'grant', ['recipientOrganization_latestIncomeBand'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grant_recipientOrganization_latestIncomeBand'), table_name='grant')
    op.drop_index(op.f('ix_grant_recipientOrganization_idCanonical'), table_name='grant')
    op.drop_index(op.f('ix_grant_recipientOrganization_ageAtGrantBands'), table_name='grant')
    op.drop_index(op.f('ix_grant_plannedDates_durationBand'), table_name='grant')
    op.drop_index(op.f('ix_grant_geoImdBand'), table_name='grant')
    op.drop_index(op.f('ix_grant_geoCty'), table_name='grant')
    op.drop_index(op.f('ix_grant_geoCtry'), table_name='grant')
    op.drop_index(op.f('ix_grant_awardDateYear'), table_name='grant')
    op.drop_index(op.f('ix_grant_awardDate'), table_name='grant')
    op.drop_index(op.f('ix_grant_amountAwardedBand'), table_name='grant')
    op.drop_index(op.f('ix_grant_amountAwarded'), table_name='grant')
    op.drop_column('grant', 'recipientOrganization_registrationDate')
    op.drop_column('grant', 'recipientOrganization_latestIncomeDate')
    op.drop_column('grant', 'recipientOrganization_latestIncomeBand')
    op.drop_column('grant', 'recipientOrganization_latestIncome')
    op.drop_column('grant', 'recipientOrganization_idCanonical')
    op.drop_column('grant', 'recipientOrganization_ageAtGrantBands')
    op.drop_column('grant', 'recipientOrganization_ageAtGrant')
    op.drop_column('grant', 'plannedDates_durationBand')
    op.drop_column('grant', 'geoRu11ind')
    op.drop_column('grant', 'geoRgn')
    op.drop_column('grant', 'geoPcon')
    op.drop_column('grant', 'geoOac11')
    op.drop_column('grant', 'geoLong')
    op.drop_column('grant', 'geoLaua')
    op.drop_column('grant', 'geoLat')
    op.drop_column('grant', 'geoImdBand')
    op.drop_column('grant', 'geoImd')
    op.drop_column('grant', 'geoCty')
    op.drop_column('grant', 'geoCtry')
    op.drop_column('grant', 'amountAwardedBand')
    # ### end Alembic commands ###
