"""=Add funding organisation type

Revision ID: 3ab75b91821d
Revises: 4d1ddc1ec574
Create Date: 2020-11-09 16:01:55.749837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab75b91821d'
down_revision = '4d1ddc1ec574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant', sa.Column('insights_funding_org_type', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_grant_insights_funding_org_type'), 'grant', ['insights_funding_org_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grant_insights_funding_org_type'), table_name='grant')
    op.drop_column('grant', 'insights_funding_org_type')
    # ### end Alembic commands ###
