"""empty message

Revision ID: 4651fcef5d5c
Revises: f03bda3c2b81
Create Date: 2019-09-25 13:43:51.144834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4651fcef5d5c'
down_revision = 'f03bda3c2b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_grant_dataset'), 'grant', ['dataset'], unique=False)
    op.create_index(op.f('ix_grant_id'), 'grant', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grant_id'), table_name='grant')
    op.drop_index(op.f('ix_grant_dataset'), table_name='grant')
    # ### end Alembic commands ###
