"""empty message

Revision ID: 5385fa1eceaa
Revises: 4651fcef5d5c
Create Date: 2019-09-25 23:07:17.370332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5385fa1eceaa'
down_revision = '4651fcef5d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_grant_recipientOrganization_charityNumber'), 'grant', ['recipientOrganization_charityNumber'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_companyNumber'), 'grant', ['recipientOrganization_companyNumber'], unique=False)
    op.drop_index('ix_by_funder_type', table_name='grant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_by_funder_type', 'grant', ['fundingOrganization_type', 'id', 'recipientOrganization_idCanonical', 'fundingOrganization_id'], unique=False)
    op.drop_index(op.f('ix_grant_recipientOrganization_companyNumber'), table_name='grant')
    op.drop_index(op.f('ix_grant_recipientOrganization_charityNumber'), table_name='grant')
    # ### end Alembic commands ###
