"""empty message

Revision ID: 945ec985c8c0
Revises: 5385fa1eceaa
Create Date: 2019-10-01 16:51:29.265949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945ec985c8c0'
down_revision = '5385fa1eceaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant', sa.Column('geoLsoa11', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('geoOa11', sa.String(), nullable=True))
    op.add_column('postcode', sa.Column('lsoa11', sa.String(), nullable=True))
    op.add_column('postcode', sa.Column('oa11', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postcode', 'oa11')
    op.drop_column('postcode', 'lsoa11')
    op.drop_column('grant', 'geoOa11')
    op.drop_column('grant', 'geoLsoa11')
    # ### end Alembic commands ###
