"""change orgid type

Revision ID: 99c803e42509
Revises: 0f2e975ac1a6
Create Date: 2019-03-01 10:27:37.565281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c803e42509'
down_revision = '0f2e975ac1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'orgid',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'orgid',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
