"""org_type index

Revision ID: d8db1577dbc1
Revises: ff5ee12e8263
Create Date: 2019-03-01 12:58:34.824948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8db1577dbc1'
down_revision = 'ff5ee12e8263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_organisation_org_type'), 'organisation', ['org_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisation_org_type'), table_name='organisation')
    # ### end Alembic commands ###
