"""empty message

Revision ID: e152bfbce39c
Revises: d8db1577dbc1
Create Date: 2019-08-30 13:41:28.922756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e152bfbce39c'
down_revision = 'd8db1577dbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant',
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amountAwarded', sa.BigInteger(), nullable=True),
    sa.Column('awardDate', sa.Date(), nullable=True),
    sa.Column('awardDateYear', sa.Integer(), nullable=True),
    sa.Column('plannedDates_startDate', sa.Date(), nullable=True),
    sa.Column('plannedDates_endDate', sa.Date(), nullable=True),
    sa.Column('plannedDates_duration', sa.Integer(), nullable=True),
    sa.Column('recipientOrganization_id', sa.String(), nullable=True),
    sa.Column('recipientOrganization_idScheme', sa.String(), nullable=True),
    sa.Column('recipientOrganization_name', sa.String(), nullable=True),
    sa.Column('recipientOrganization_charityNumber', sa.String(), nullable=True),
    sa.Column('recipientOrganization_companyNumber', sa.String(), nullable=True),
    sa.Column('recipientOrganization_postalCode', sa.String(), nullable=True),
    sa.Column('fundingOrganization_id', sa.String(), nullable=True),
    sa.Column('fundingOrganization_name', sa.String(), nullable=True),
    sa.Column('fundingOrganization_department', sa.String(), nullable=True),
    sa.Column('grantProgramme_title', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dataset', 'id')
    )
    op.create_index(op.f('ix_grant_currency'), 'grant', ['currency'], unique=False)
    op.create_index(op.f('ix_grant_fundingOrganization_id'), 'grant', ['fundingOrganization_id'], unique=False)
    op.create_index(op.f('ix_grant_fundingOrganization_name'), 'grant', ['fundingOrganization_name'], unique=False)
    op.create_index(op.f('ix_grant_grantProgramme_title'), 'grant', ['grantProgramme_title'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_id'), 'grant', ['recipientOrganization_id'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_idScheme'), 'grant', ['recipientOrganization_idScheme'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_postalCode'), 'grant', ['recipientOrganization_postalCode'], unique=False)
    op.create_table('postcode',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ctry', sa.String(), nullable=True),
    sa.Column('cty', sa.String(), nullable=True),
    sa.Column('laua', sa.String(), nullable=True),
    sa.Column('pcon', sa.String(), nullable=True),
    sa.Column('rgn', sa.String(), nullable=True),
    sa.Column('imd', sa.Integer(), nullable=True),
    sa.Column('ru11ind', sa.String(), nullable=True),
    sa.Column('oac11', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcode')
    op.drop_index(op.f('ix_grant_recipientOrganization_postalCode'), table_name='grant')
    op.drop_index(op.f('ix_grant_recipientOrganization_idScheme'), table_name='grant')
    op.drop_index(op.f('ix_grant_recipientOrganization_id'), table_name='grant')
    op.drop_index(op.f('ix_grant_grantProgramme_title'), table_name='grant')
    op.drop_index(op.f('ix_grant_fundingOrganization_name'), table_name='grant')
    op.drop_index(op.f('ix_grant_fundingOrganization_id'), table_name='grant')
    op.drop_index(op.f('ix_grant_currency'), table_name='grant')
    op.drop_table('grant')
    # ### end Alembic commands ###
