"""empty message

Revision ID: f03bda3c2b81
Revises: 1a46d2911914
Create Date: 2019-09-04 23:20:50.964953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03bda3c2b81'
down_revision = '1a46d2911914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grant', sa.Column('fundingOrganization_type', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_organisationType', sa.String(), nullable=True))
    op.add_column('grant', sa.Column('recipientOrganization_postalCodeCanonical', sa.String(), nullable=True))
    op.create_index(op.f('ix_grant_fundingOrganization_type'), 'grant', ['fundingOrganization_type'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_organisationType'), 'grant', ['recipientOrganization_organisationType'], unique=False)
    op.create_index(op.f('ix_grant_recipientOrganization_postalCodeCanonical'), 'grant', ['recipientOrganization_postalCodeCanonical'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grant_recipientOrganization_postalCodeCanonical'), table_name='grant')
    op.drop_index(op.f('ix_grant_recipientOrganization_organisationType'), table_name='grant')
    op.drop_index(op.f('ix_grant_fundingOrganization_type'), table_name='grant')
    op.drop_column('grant', 'recipientOrganization_postalCodeCanonical')
    op.drop_column('grant', 'recipientOrganization_organisationType')
    op.drop_column('grant', 'fundingOrganization_type')
    # ### end Alembic commands ###
