"""add source and last_updated field

Revision ID: ff5ee12e8263
Revises: 99c803e42509
Create Date: 2019-03-01 10:47:20.998301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5ee12e8263'
down_revision = '99c803e42509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('organisation', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'source')
    op.drop_column('organisation', 'last_updated')
    # ### end Alembic commands ###
